systemd:
  units:
    - name: update-engine.service
      mask: true
      enabled: false
    - name: locksmithd.service
      mask: true
      enabled: false
storage:
  files:
    - path: /etc/flatcar/update.conf
      filesystem: root
      mode: 0644
      contents:
        inline: |
          REBOOT_STRATEGY=off
    - path: /etc/ssh/sshd_config
      filesystem: root
      mode: 0600
      contents:
        inline: |
          KexAlgorithms ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,curve25519-sha256@libssh.org
          Ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,chacha20-poly1305@openssh.com
          MACs hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com,hmac-sha2-512-etm@openssh.com
          UsePrivilegeSeparation sandbox
          Subsystem sftp internal-sftp
          UseDNS no
          PermitRootLogin no
          AllowUsers core
          AuthenticationMethods publickey
          ClientAliveInterval 180
          UsePAM yes
          PrintLastLog no
          PrintMotd no
